/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1015ddfc-d9c0-4103-b9a2-eef6f3d0e7f2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_o2Key9oMo",
    "aws_user_pools_web_client_id": "v4rub7h2bp7m3v5rn1v5i3tvc",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://73xluklflvbtrdxgl4n5bsdol4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-o27w2fj42rdn5ovfaqdmr3he2m",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://lcelmn1pa2.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "EmailRequests",
            "endpoint": "https://x2cb89nemc.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "KayaPayments",
            "endpoint": "https://fqpsy8p07k.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "KayaGroupsAPI",
            "endpoint": "https://ensfg4uu9a.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "KayaParticipantsAPI",
            "endpoint": "https://zezhplh8ck.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "ReqHandlerAPI",
            "endpoint": "https://en5xhka94d.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "kayastaticresourcestoragebucket153016-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
